import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import '../models/appointment.dart';
import '../models/teacher.dart';
import '../services/supabase_service.dart';
import '../utils/app_theme.dart';
import '../widgets/teacher_avatar.dart';

/// Student-side screen to book an appointment with a specific teacher.
class BookAppointmentScreen extends StatefulWidget {
  final Teacher teacher;
  const BookAppointmentScreen({super.key, required this.teacher});

  @override
  State<BookAppointmentScreen> createState() => _BookAppointmentScreenState();
}

class _BookAppointmentScreenState extends State<BookAppointmentScreen> {
  DateTime _selectedDate = DateTime.now().add(const Duration(days: 1));
  TimeOfDay _selectedTime = const TimeOfDay(hour: 10, minute: 0);
  final _purposeCtrl = TextEditingController();
  bool _submitting = false;

  @override
  void dispose() {
    _purposeCtrl.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 60)),
      builder: (context, child) => Theme(
        data: Theme.of(context).copyWith(
          colorScheme: const ColorScheme.light(
            primary: AppTheme.primaryBlue,
            onPrimary: Colors.white,
            surface: Colors.white,
            onSurface: AppTheme.textPrimary,
          ),
        ),
        child: child!,
      ),
    );
    if (picked != null) setState(() => _selectedDate = picked);
  }

  Future<void> _pickTime() async {
    final picked = await showTimePicker(
      context: context,
      initialTime: _selectedTime,
      builder: (context, child) => Theme(
        data: Theme.of(context).copyWith(
          colorScheme: const ColorScheme.light(
            primary: AppTheme.primaryBlue,
            onPrimary: Colors.white,
            surface: Colors.white,
            onSurface: AppTheme.textPrimary,
          ),
        ),
        child: child!,
      ),
    );
    if (picked != null) setState(() => _selectedTime = picked);
  }

  String _formatDate(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  String _formatTime(TimeOfDay t) =>
      '${t.hour.toString().padLeft(2, '0')}:${t.minute.toString().padLeft(2, '0')}';

  Future<void> _submit() async {
    if (_purposeCtrl.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a purpose for the appointment')),
      );
      return;
    }
    setState(() => _submitting = true);

    try {
      final svc = context.read<SupabaseService>();
      final student = svc.currentStudent;
      final studentId = student?.studentId ?? 'unknown';
      final studentName = student?.name ?? 'Student';

      final appt = Appointment(
        id: '', // generated by DB
        teacherInitial: widget.teacher.initial,
        studentId: studentId,
        studentName: studentName,
        date: _formatDate(_selectedDate),
        time: _formatTime(_selectedTime),
        purpose: _purposeCtrl.text.trim(),
        status: 'pending',
        createdAt: '',
      );

      await svc.createAppointment(appt);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Appointment request sent to ${widget.teacher.name}'),
          backgroundColor: AppTheme.successGreen,
        ),
      );
      Navigator.pop(context, true);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e'), backgroundColor: AppTheme.errorRed),
      );
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final teacher = widget.teacher;

    return Scaffold(
      backgroundColor: AppTheme.scaffoldBg,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        scrolledUnderElevation: 0.5,
        title: Text('Book Appointment', style: GoogleFonts.poppins(
          fontSize: 18, fontWeight: FontWeight.w600, color: AppTheme.textPrimary,
        )),
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // Teacher info card
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(AppTheme.radiusL),
              border: Border.all(color: AppTheme.borderLight),
              boxShadow: AppTheme.cardShadow,
            ),
            child: Row(
              children: [
                TeacherAvatar(
                  initial: teacher.initial,
                  profilePicUrl: teacher.profilePic,
                  radius: 26,
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(teacher.name, style: GoogleFonts.poppins(
                        fontSize: 15, fontWeight: FontWeight.w600, color: AppTheme.textPrimary,
                      )),
                      Text(teacher.designation, style: GoogleFonts.poppins(
                        fontSize: 12, color: AppTheme.textSecondary,
                      )),
                      Text(teacher.homeDepartment, style: GoogleFonts.poppins(
                        fontSize: 11, color: AppTheme.textHint,
                      )),
                    ],
                  ),
                ),
                AppTheme.chip(teacher.initial, bg: AppTheme.primaryBlueLight, fg: AppTheme.primaryBlue),
              ],
            ),
          ),

          const SizedBox(height: 24),

          // Date picker
          Text('APPOINTMENT DATE', style: AppTheme.labelUpper),
          const SizedBox(height: 8),
          GestureDetector(
            onTap: _pickDate,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(AppTheme.radiusM),
                border: Border.all(color: AppTheme.borderLight),
              ),
              child: Row(
                children: [
                  const Icon(Icons.calendar_today_outlined, size: 18, color: AppTheme.primaryBlue),
                  const SizedBox(width: 12),
                  Text(
                    _formatDate(_selectedDate),
                    style: GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w500, color: AppTheme.textPrimary),
                  ),
                  const Spacer(),
                  const Icon(Icons.chevron_right, size: 20, color: AppTheme.textHint),
                ],
              ),
            ),
          ),

          const SizedBox(height: 20),

          // Time picker
          Text('APPOINTMENT TIME', style: AppTheme.labelUpper),
          const SizedBox(height: 8),
          GestureDetector(
            onTap: _pickTime,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(AppTheme.radiusM),
                border: Border.all(color: AppTheme.borderLight),
              ),
              child: Row(
                children: [
                  const Icon(Icons.access_time, size: 18, color: AppTheme.primaryBlue),
                  const SizedBox(width: 12),
                  Text(
                    _formatTime(_selectedTime),
                    style: GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w500, color: AppTheme.textPrimary),
                  ),
                  const Spacer(),
                  const Icon(Icons.chevron_right, size: 20, color: AppTheme.textHint),
                ],
              ),
            ),
          ),

          const SizedBox(height: 20),

          // Purpose
          Text('PURPOSE', style: AppTheme.labelUpper),
          const SizedBox(height: 8),
          TextField(
            controller: _purposeCtrl,
            maxLines: 4,
            style: GoogleFonts.poppins(fontSize: 14, color: AppTheme.textPrimary),
            decoration: InputDecoration(
              hintText: 'e.g. Discuss project, Counselling, Thesis guidance...',
              hintStyle: GoogleFonts.poppins(fontSize: 13, color: AppTheme.textHint),
              filled: true,
              fillColor: Colors.white,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(AppTheme.radiusM),
                borderSide: BorderSide(color: AppTheme.borderLight),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(AppTheme.radiusM),
                borderSide: BorderSide(color: AppTheme.borderLight),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(AppTheme.radiusM),
                borderSide: const BorderSide(color: AppTheme.primaryBlue),
              ),
            ),
          ),

          const SizedBox(height: 32),

          // Submit
          SizedBox(
            width: double.infinity,
            height: 50,
            child: ElevatedButton(
              onPressed: _submitting ? null : _submit,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primaryBlue,
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(AppTheme.radiusM),
                ),
                disabledBackgroundColor: AppTheme.primaryBlue.withValues(alpha: 0.5),
              ),
              child: _submitting
                  ? const SizedBox(
                      width: 22, height: 22,
                      child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5),
                    )
                  : Text('Send Appointment Request', style: GoogleFonts.poppins(
                      fontSize: 15, fontWeight: FontWeight.w600,
                    )),
            ),
          ),

          const SizedBox(height: 16),
          Center(
            child: Text(
              'The teacher will review and accept/reject your request.',
              style: GoogleFonts.poppins(fontSize: 11, color: AppTheme.textHint, fontStyle: FontStyle.italic),
              textAlign: TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }
}
